### ISSUE TITLE
Implementation snapshot b3

### ISSUE THREAD

**Issue by nyaxt** [WICG/webpackage#350]
We would like to prepare another implementation snapshot `b3` to incorporate the recent changes to the format.
Our plan is to ship Chrome M73 with `b3` support.

## Highlight of changes since `b2`

of which we would definitely want to make it in `b3`:
- [x] `Variants` header-based request matching (post #285)
  - [x] https://github.com/WICG/webpackage/pull/285
  - [x] https://github.com/WICG/webpackage/pull/360
  - [x] https://github.com/httpwg/http-extensions/pull/735
  - [x] https://github.com/httpwg/http-extensions/issues/570
  - [x] Version the Variant headers (httpwg/http-extensions#747)
- [x] Header bans (#336, #340)
- [x] Reject uncachable and incomplete responses (#326)
- [x] UTF-8 decode the URL string (#346) 
- [x] Prevent content-type sniffing (#354)

**Comment by twifkak** [comment]
Also include httpwg/http-extensions#735 per comments on #285.

**Comment by nyaxt** [comment]
@twifkak noted. Am I correct that it is part of #285?

**Comment by nyaxt** [comment]
I just went over list of open PRs and found https://github.com/WICG/webpackage/pull/121 is not yet resolved.
@jyasskin @davidben : I'd like to hear your latest thoughts. Do you think we should include the change in b3?

**Comment by jyasskin** [comment]
I'm currently inclined not to make the change in #121. We should encourage folks to use a unique URL for each version of the OCSP response, but signing it all together seemed to cause some problems for the Intermediate's serving infrastructure for not much benefit. (@twifkak had more details about the problems.)

**Comment by jyasskin** [comment]
I realized we should version our `Variants` headers too: https://github.com/httpwg/http-extensions/issues/747. It's not absolutely essential, since they're always embedded into a versioned SXG file, but it reduces the risk that it'll leak into the rest of the ecosystem.

**Comment by twifkak** [comment]
I believe this snapshot also needs to include the httpbis-header-structure upgrade, per http://crrev.com/c/1420506.

**Comment by EverlastingBugstopper** [comment]
Is there a timeline for when this will be included in the implementation checkpoints? https://tools.ietf.org/html/draft-yasskin-httpbis-origin-signed-exchanges-impl-02 has expired as of March 8

**Comment by jyasskin** [comment]
I-D expirations don't really mean anything, but you're right that we're overdue for publishing the -03 draft. I've started on it and should have a first version out for review today. Once I merge that, it'll be available at https://wicg.github.io/webpackage/draft-yasskin-httpbis-origin-signed-exchanges-impl.html. I can't publish anything to the IETF's server until [March 23](https://datatracker.ietf.org/submit/), but I may leave it open for several days to a week after that to make sure folks have time to review it.

Sorry for the slowness.

**Comment by EverlastingBugstopper** [comment]
Any chance this will be merged?

**Comment by jyasskin** [comment]
https://tools.ietf.org/html/draft-yasskin-httpbis-origin-signed-exchanges-impl-03 is finally submitted. Sorry for the delay.
