### ISSUE TITLE
[Meta] A long term plan for subresource loading

### ISSUE THREAD

**Issue by hayatoito** [WICG/webpackage#648]
Hi folks!

Let us share the current status and a future plan about [Subresource Loading with Web Bundles].

## Status:

- We're starting an origin trial in Chrome (M90 - M92). [Landing page].

If we don't find any significant issue in OT and this feature is promising, as the next step, we'll work on addressing any
blocking issues or support feature requests, considering feedback from OT, so that we can ship
MVP (*v1*).

## Tentative plan (No ETA):

Note: The following mentions only *features*. Any standard works or other tasks are not included.

### v1 (We consider MVP should be shipped with these features)

- [ ] The core part: [Subresource Loading with Web Bundles]
- [ ] The extension: [Support opaque origin iframes]
  - [ ] Change urn:uuid to other scheme (TODO: File an issue)
- [ ] Make primary URL optional (#616)
  - [ ] Needs to update the bundle format.
- [ ] Support a relative URL of a resource in a bundle (#647)
  - [ ] Needs to update the bundle format?
- [ ] New syntax: Use `<script>` tag and define its scheme
  - [ ] TODO: File an issue.
- [ ] CORP and COEP (#644)
- [ ] Increment the bundle format version?

### v2 (We consider these are important, but not absolutely required for shipping MVP)

- [ ] Subsetting ([Resource Batch Preloading], [Resource Bundles])
  - [Chromium side design doc](https://docs.google.com/document/d/159wbsjWh13xpwZbK-4LNNHcbtRROiXAJSabunJXWEzs/edit), based on [Resource Bundles] proposal.

### v3 (Strawperson ideas, which are not triaged well yet)

- [ ] Use the index section as an alternative of a “resources=” attribute value
  ([cab] mentions this)
  - [ ] TODO: File an issue on GitHub.
- [ ] Declare dependencies to external bundles (#596, #40, [cab])
  - [ ] Needs to update the bundle format
- [ ] Resource Hints with webbundle
  - `<link rel=prefetch-for-navigation href=”//example.com/nextpage.wbn” page=”//example.com/nextpage.html”>`
  - [ ] Needs a concrete proposal.
- [ ] [Content Addressable Bundles]

We'll try to keep this plan up-to-date.

[subresource loading with web bundles]:
  https://github.com/WICG/webpackage/blob/main/explainers/subresource-loading.md
[support opaque origin iframes]:
  https://github.com/WICG/webpackage/blob/main/explainers/subresource-loading-opaque-origin-iframes.md
[landing page]:
  https://chromium.googlesource.com/chromium/src.git/+/refs/heads/main/content/browser/web_package/subresource_loading_origin_trial.md
[cab]:
  https://github.com/hayatoito/webpackage/blob/content-addressable-bundles/explainers/content-addressable-bundles.md
[content addressable bundles]:
  https://github.com/hayatoito/webpackage/blob/content-addressable-bundles/explainers/content-addressable-bundles.md
[resource batch preloading]:
  https://gist.github.com/littledan/e01801001c277b0be03b1ca54788505e
[resource bundles]: https://gist.github.com/WICG/resource-bundles

**Comment by hayatoito** [comment]
We've split the previous explainer into the core part and the extension part (PR #645).

@littledan 

We've heard that you would work on [Resource Batch Preloading proposal](https://gist.github.com/littledan/e01801001c277b0be03b1ca54788505e).

We are wondering how the current *core* part is close enough so that Resource Batch Preloading can be explained based on the current core part (with v1 features).

If you find something which might make it difficult  for us to have a Resource Batch Preloading proposal, we'd appreciate your feedback!

Regarding syntax, we've not decided anything about a new `<script type=xxxx>....</script>` syntax. It would be nice that we can have a good syntax which can be used either in v1 or Resource Batch Preloading proposal without much difference. We'd appreciate if you have any ideas!

Thanks!

**Comment by littledan** [comment]
This outline and layering looks good to me. Here is my view of next steps on my side (to rephrase what I wrote in https://github.com/WICG/resource-bundles/issues/21):
- Now that the IETF WPACK WG has adopted the bundled responses format, a new repository will be created for the bundle format. IETF WPACK WG will schedule an interrum meeting to discuss further format issues that you listed above. I am available to help @jyasskin with this repository if needed--I think it could be useful to include some of the text in the resource-bundles repository there.
- The "resource bundles" repository will transition to being the "batch prefetching" repository, to house the subset-based loading technique, now that the format is developed elsewhere. @cjtenny and I plan to work on the core proposal and have a document to share in a week or two. We apologize for our delay. This document will contain all concrete API surface details.

The API I was picturing looks quite similar to your [Chromium design doc](https://docs.google.com/document/d/159wbsjWh13xpwZbK-4LNNHcbtRROiXAJSabunJXWEzs/edit) with the exception of the cache name, which I asked you about in a doc comment. What was the motivation for using a named cache, rather than having these simply be entries in the main HTTP cache?

**Comment by horo-t** [comment]
> The API I was picturing looks quite similar to your [Chromium design doc](https://docs.google.com/document/d/159wbsjWh13xpwZbK-4LNNHcbtRROiXAJSabunJXWEzs/edit) with the exception of the cache name, which I asked you about in a doc comment. What was the motivation for using a named cache, rather than having these simply be entries in the main HTTP cache?

It is because [the prototype CL](https://chromium-review.googlesource.com/c/chromium/src/+/2791026) is using Cache Storage to store each resources. If we will use the HTTP cache, we don’t need this cache name field.
But there are some benefits of using Cache Storage. The web developers can manipulate the resources in the cache using Cache Storage APIs. And also we already have good DevTools support for Cache Storage.

**Comment by ShivanKaul** [comment]
This is a little late, but some feedback on the plan:
1. Are there use cases apart from the https://github.com/WICG/webpackage/issues/624 use case enabled by the UUID scheme? That just sounds bad overall for the web - "The ad JS can render an ad by setting the src of an iframe to a resource that's inside the bundle, but nothing on the client can read or modify the ad HTML because the resources are opaque." This is exactly the fear articulated in https://brave.com/web-standards-at-brave/3-web-bundles/ and https://github.com/WICG/webpackage/issues/551
2. Subsetting via preloading as in https://github.com/WICG/bundle-preloading/  sounds much better for letting the client decide which resources it might not want to fetch (both for caching and content blocking and just overall preventing unnecessary bytes from being downloaded). I'm very disappointed that that is not making it into v1. 

Please let me know if I'm mistaken in my understanding, it's hard keeping up with the several documents related to Web Bundles/WPACK.

**Comment by hayatoito** [comment]
Thanks for the feedback!

Re 1:
https://github.com/WICG/webpackage/issues/623 has a proposal using `<iframe opaque>`-ish, however, it seems no one is actively working on that. It seems we need a person who drives an alternative idea.

Re 2:
That's surely targeted in v2. We hope we can cover more wider use cases there.

**Comment by jeffkaufman** [comment]
Re 1: from an ads perspective, something similar to subresource bundles where *extensions* were able to read/modify the ad HTML would be completely fine.  The goal is to isolate ads from (a) other ads and (b) JavaScript and running in the context of the publisher page.

**Comment by ShivanKaul** [comment]
For 1: The concern is that the way these UUIDs will be generated is by the bundler toolchain, meaning that every resource, even if it's the same across different websites, will have a unique (by definition) ID. I get that current bundlers can do that as well, but this is standardizing and incentivizing that practice. #623 sounds like a much better approach (and I share the concerns articulated over there). 

For 2: it's good that it's in scope, but what is the fallback option here if a server refuses to acknowledge the proposed `Resources` header and always sends the entire bundle? Seems like the most client-friendly approach would be to do it in v1 along with the rest of the push towards subresource bundle loading instead of trying to fix things later on given what is at stake here is clients downloading unnecessary bytes, which hurts exactly those users whose needs we should be prioritizing.

**Comment by hayatoito** [comment]
Thanks.

For 1:

Re #623, tt seems there is no activity for a year. Can we expect we have a progress on that?

Re UUID approach, we're not aware whether there is any particular concern, technically or theoretically, on using UUID.
We'd appreciate if someone has a particular practical concern of using UUID, which is hopefully actionable for us.


For 2:
A good question. I think Bundle Preloading's [Backward compatibility section](https://github.com/WICG/bundle-preloading/blob/main/subresource-loading-server.md#backwards-compatibility) explains that well.
